Add php7-zip package
linuxserver/docker-piwigo pull request #48
Opened 2021-06-29 22:40 UTC by TheSpad

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

 - [x] I have read the [contributing](https://github.com/linuxserver/docker-piwigo/blob/master/.github/CONTRIBUTING.md) guideline and understand that I have made the correct modifications

------------------------------

## Description:
Adds php7-zip package to the image. Closes #34.

## Benefits of this PR and context:

## How Has This Been Tested?

## Source / References:

2021-06-29 23:42 UTC, thelamer requested changes
Should we add this to changelog?

2021-06-30 07:59 UTC, TheSpad commented
Added changelog entry. Also taken the opportunity to rebase to 3.14 as this image doesn't get touched very often.

2021-06-30 12:33 UTC, aptalca approved these changes

2021-06-30 12:34 UTC, merged

2021-07-01 00:42 UTC, lbesnard commented
awesome thanks!